openapi: '3.0.3'
info:
  title: Users
  version: '1.0.0'
  description: 'Users API'
  contact:
    name: Amir Suboh
    email: asuboh@eagles.bridgewater.edu

servers:
  - url: https://localhost:3001
    description: Local development server
paths:
  /user:
    post:
      description: Create a New User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              firstName: John
              lastName: Doe
              username: johndoe
              email: jdoe@g.com
              password: 12345678

      responses:
        '201':
          description: User Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  _id:
                    type: string
        '400':
          description: Failed to Create User; Invalid inputs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Error Creating User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    User:
      type: object
      required:
        - username
        - firstName
        - lastName
        - email
        - password
      properties:
        username:
          type: string
          minLength: 5
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
          minLength: 8
        email:
          type: string
    InternalServerError: 
      type: object
      properties:
        message:
          type: string
    ValidationError:
      type: object
      properties:
        message:
          type: string
